/**
 * @survscribe/types -- the shared TypeScript view of the SurvScribe API v1 contract.
 *
 * `schema.d.ts` is generated by `openapi-typescript` from
 * `documentation/architecture/api-contract/openapi.yaml`, which is itself generated from
 * the migration DDL. Nothing in this package is hand-maintained except this file, which
 * exists only to give the generated shapes names worth importing: `components["schemas"]
 * ["AssessmentLineItem"]` is accurate but nobody wants to read it at a call site.
 *
 * Regenerate with `pnpm --filter @survscribe/types generate`. Never edit `schema.d.ts`.
 */
import type { components, operations, paths } from "./schema";

export type { components, operations, paths };

type Schemas = components["schemas"];

/* ------------------------------------------------------------------ envelopes */

/** ADR-0004 section 2. Every successful response has this shape. */
export interface ApiSuccess<T> {
  success: true;
  data: T;
  error: null;
  meta: Schemas["Meta"] | null;
}

/** ADR-0004 section 3. */
export type ApiErrorBody = Schemas["ErrorResponse"];
export type ApiError = Schemas["ApiError"];
export type ErrorCode = Schemas["ErrorCode"];
export type Meta = Schemas["Meta"];

export type ApiResponse<T> = ApiSuccess<T> | ApiErrorBody;

export function isApiError<T>(r: ApiResponse<T>): r is ApiErrorBody {
  return r.success === false;
}

/**
 * A rupee amount. Every NUMERIC crosses the wire as a decimal string, never a JSON
 * number: IEEE-754 cannot hold NUMERIC(15,2) exactly, and FR-15.1 gate 1 requires the
 * Section F totals to reconcile to the rupee. Do not `parseFloat` these for arithmetic --
 * use the deterministic decimal engine.
 */
export type Decimal = string;

/* ------------------------------------------------------------------ identity */

export type User = Schemas["User"];
export type Store = Schemas["Store"];
export type Session = Schemas["Session"];
export type StoreInvite = Schemas["StoreInvite"];
export type AuthSession = Schemas["AuthSession"];
export type TokenPair = Schemas["TokenPair"];
export type DeviceInfo = Schemas["DeviceInfo"];
export type RegisterRequest = Schemas["RegisterRequest"];
export type LoginRequest = Schemas["LoginRequest"];
export type RefreshRequest = Schemas["RefreshRequest"];
export type OtpRequest = Schemas["OtpRequest"];
export type OtpVerifyRequest = Schemas["OtpVerifyRequest"];
export type OtpChallengeAccepted = Schemas["OtpChallengeAccepted"];
export type AcceptInviteRequest = Schemas["AcceptInviteRequest"];

/* ------------------------------------------------------------------ claim workflow */

export type Claim = Schemas["Claim"];
export type ClaimCreate = Schemas["ClaimCreate"];
export type ClaimUpdate = Schemas["ClaimUpdate"];

export type PolicyDetail = Schemas["PolicyDetail"];
export type PolicySection = Schemas["PolicySection"];
export type ContactLog = Schemas["ContactLog"];
export type PreservationNotice = Schemas["PreservationNotice"];
export type SiteVisit = Schemas["SiteVisit"];
export type CauseInvestigation = Schemas["CauseInvestigation"];
export type ChronologyEvent = Schemas["ChronologyEvent"];
export type DamageItem = Schemas["DamageItem"];
export type MediaAttachment = Schemas["MediaAttachment"];
export type SurveyDocument = Schemas["Document"];
export type DocumentDamageLink = Schemas["DocumentDamageLink"];
export type DocumentLineItem = Schemas["DocumentLineItem"];
export type RequisitionNotice = Schemas["RequisitionNotice"];
export type PreliminarySurveyReport = Schemas["PreliminarySurveyReport"];
export type DiscrepancyFlag = Schemas["DiscrepancyFlag"];
export type AssessmentHead = Schemas["AssessmentHead"];
export type AssessmentLineItem = Schemas["AssessmentLineItem"];
export type SalvageRecord = Schemas["SalvageRecord"];
export type CoverageOpinion = Schemas["CoverageOpinion"];
export type FinalSurveyReport = Schemas["FinalSurveyReport"];
export type PreSubmissionAudit = Schemas["PreSubmissionAudit"];
export type ReportDispatch = Schemas["ReportDispatch"];
export type AuditLog = Schemas["AuditLog"];

/* ------------------------------------------------------------------ actions */

export type StageAdvanceRequest = Schemas["StageAdvanceRequest"];
export type ApprovalGateRequest = Schemas["ApprovalGateRequest"];
export type ExportRequest = Schemas["ExportRequest"];
export type SignOffRequest = Schemas["SignOffRequest"];

/* ------------------------------------------------------------------ media & sync */

export type MediaUploadInit = Schemas["MediaUploadInit"];
export type MediaUploadTicket = Schemas["MediaUploadTicket"];
export type SyncChange = Schemas["SyncChange"];
export type SyncPushRequest = Schemas["SyncPushRequest"];
export type SyncPushResult = Schemas["SyncPushResult"];
export type SyncPullResult = Schemas["SyncPullResult"];
export type SyncConflict = Schemas["SyncConflict"];

/* ------------------------------------------------------------------ enums */

export type ClaimStatus = Schemas["ClaimStatus"];
export type PerilType = Schemas["PerilType"];
export type PolicyType = Schemas["PolicyType"];
export type HeadCategory = Schemas["HeadCategory"];
export type PolicySectionHead = Schemas["PolicySectionHead"];
export type VisitType = Schemas["VisitType"];
export type ChronologyEventType = Schemas["ChronologyEventType"];
export type DamageSeverity = Schemas["DamageSeverity"];
export type DamageRecommendation = Schemas["DamageRecommendation"];
export type Uom = Schemas["Uom"];
export type MediaType = Schemas["MediaType"];
export type DocumentType = Schemas["DocumentType"];
export type OcrStatus = Schemas["OcrStatus"];
export type AuditStatus = Schemas["AuditStatus"];
export type DiscrepancyCode = Schemas["DiscrepancyCode"];
export type DiscrepancySeverity = Schemas["DiscrepancySeverity"];
export type DiscrepancyStatus = Schemas["DiscrepancyStatus"];
export type DisposalMode = Schemas["DisposalMode"];
export type PerilAdmissibility = Schemas["PerilAdmissibility"];
export type WarrantyComplianceStatus = Schemas["WarrantyComplianceStatus"];
export type SurveyorRecommendation = Schemas["SurveyorRecommendation"];
export type ReportStatus = Schemas["ReportStatus"];
export type AuditGateResult = Schemas["AuditGateResult"];
export type AuditAction = Schemas["AuditAction"];
export type SyncOperation = Schemas["SyncOperation"];
export type SyncStatus = Schemas["SyncStatus"];
export type RoleScope = Schemas["RoleScope"];
export type UserStatus = Schemas["UserStatus"];
export type DevicePlatform = Schemas["DevicePlatform"];
export type SessionStatus = Schemas["SessionStatus"];
export type DispatchChannel = Schemas["DispatchChannel"];
export type DispatchStatus = Schemas["DispatchStatus"];
export type ContactOutcome = Schemas["ContactOutcome"];
export type FirmType = Schemas["FirmType"];

/* ------------------------------------------------------------------ constants */

/** The 15 workflow stages. `claims.current_stage` is 1-15 (FR-1.3, CR-W1). */
export const STAGE_MIN = 1;
export const STAGE_MAX = 15;

/**
 * The four points of the Human Approval Gate (FR-14.4). All four must be recorded before
 * a PSR or FSR `.docx` can be generated -- see CLAUDE.md section 14 constraint 4.
 */
export const APPROVAL_GATE_POINTS = [
  "reviewed_ai_content",
  "confirmed_factual_accuracy",
  "confirmed_calculations",
  "accepted_professional_responsibility",
] as const;

/** The seven Stage 15 compliance gates, in FR-15.1 order (D36). */
export const AUDIT_GATES = [
  "ARITHMETIC_CHECK",
  "METADATA_CONSISTENCY",
  "DEDUCTION_REMARKS",
  "PHOTO_ANNEXURE_COMPLIANCE",
  "DOCUMENT_COMPLETENESS",
  "CONTRADICTION_SCANNER",
  "HUMAN_APPROVAL_AI_GATE",
] as const;

/** Placeholder AI-4 must emit instead of inventing a fact (CLAUDE.md section 14 constraint 3). */
export const SURVEYOR_TO_VERIFY = "[SURVEYOR TO VERIFY]";
